### ISSUE TITLE
My nitpicking of filenames used inside the epub

### ISSUE THREAD

**Issue by Anangaya** [gonejack/html-to-epub#1]
First file is named as section0002.xhtml which I think should be named as section0001.xhtml (maybe reduce the number of leading zeros a bit as well. It looks out of place when there is only one file!) . I'd like the image names to be something human readable like Image-001. I guess there is a reason that the images are named like 8a9a71440f4e8d4cba76507c2d27dbb6.jpg but the only thing I feel after looking at it is a strong urge to rename them.

There are very few tools that actually converts html with images embed and without messing up the formatting. So thanks for creating it!

**Comment by gonejack** [comment]
Hi @Anangaya 

Thanks for your report about these details that I didn't notice before and I would like to resolve these when I got some time then make a reply on this issue to let you know.

**Comment by gonejack** [comment]
Done. Please do this update:
```bash
go get github.com/gonejack/html-to-epub@main
```

**Comment by Anangaya** [comment]
Yes. Thanks. now it looks fine!
