### ISSUE TITLE
possible to create TOC based on article created date?

### ISSUE THREAD

**Issue by Zane-XY** [gonejack/html-to-epub#3]
First of all, thanks for the amazing work! The `rss-to-html` and then `html-to-epub` workflow works well.

The `rss-to-html` gives the following outputs:

```
[Advanced Reactive Java][The Reactive-Streams API (part....6b0b][2015-06-15 11.46.00].html
[Advanced Reactive Java][The Reactive-Streams API (part....9b93][2015-06-13 15.15.00].html
[Advanced Reactive Java][The Reactive-Streams API (part....ec63][2015-06-15 13.34.00].html
[Advanced Reactive Java][The new Completable API (part ....43f5][2015-12-14 15.05.00].html
[Advanced Reactive Java][The new Completable API (part ....aa85][2015-12-11 15.01.00].html
[Advanced Reactive Java][When multiple subscribeOn()s d....5e49][2017-11-29 12.33.00].html
[Advanced Reactive Java][Writing a custom reactive base....139a][2016-03-20 13.18.00].html
```

The only thing troubles me is the current TOC is based on alphabetical order rather than the article created date. It shouldn't be too difficult to support this right?

**Comment by gonejack** [comment]
Hi, @Zane-XY 

Thanks for your issue.

I will check it out later when I got some time.

**Comment by gonejack** [comment]
Hi, @Zane-XY 

Output files of `rss-to-html` now has their published time as their file mod time, would you like to do a update
```
go install ithub.com/gonejack/rss-to-html@1.0.6
```

After this update you could pass generated .html files in order of published time to `html-to-epub`
```
ls -t *.html | xargs html-to-epub
```

**Comment by Zane-XY** [comment]
@gonejack 

Thanks for the updates!
I got this working by using

`ls -tr *.html | tr '\n' '\0' | xargs -0 html-to-epub`
