### ISSUE TITLE
The generated epub file is too big. Can it be optimized to reduce the file size?

### ISSUE THREAD

**Issue by nietulong** [gonejack/html-to-epub#7]
Thank you for your software, it helps me a lot.

**Comment by gonejack** [comment]
Hi, @nietulong 

AS I know there should be no large files generated by this command line.

If it's large it should caused by rich contents, since .epub files are just zip files could you unzip it first then lookup it up for  why.

If there are still any issues you are always welcome.

**Comment by nietulong** [comment]
[wechat.zip](https://github.com/user-attachments/files/17794375/wechat.zip)
这个是我的例子，生成的epub大了好多啊，应该是图片处理的问题。

**Comment by gonejack** [comment]
没有错，会下载并收纳图片。

这个命令行与其他工具的主要区别便是能解析内容下载图片并嵌入文件，以避免将来且注定的图片失效，这个特性对于资料归档非常重要，系开发这个工具的初衷。

**Comment by nietulong** [comment]
是否能优化一下图片，压缩一下大小。我目前的解决方案是生成的时候禁用网卡，缺点就是无图。

**Comment by gonejack** [comment]
倒是对图片大小不敏感，既然有这种情况，便使用 chatgpt 写了一个，希望对你有用，但未经测试

https://github.com/gonejack/smallepub

**Comment by nietulong** [comment]
效果非常好，感谢。
